export const styles = {
  colors: {
    light: '#3b3b3b',
    greenContrast: '#43B27F',
    lightMode: '#EDFDF2',
    darkMode: '#080610',
    white: '#FFF',
    greyContrast: '#93B1A6',
  },
  percentage: { eighty: '80%' },
  unitsInREMToPX: {
    six: '0.6rem',
    twelve: '1.2rem',
    fourteen: '1.4rem',
    sixteen: '1.6rem',
    twenty: '2rem',
    twentyFour: '2.4rem',
    twentyEigth: '2.8rem',
    thirty: '3rem',
    thirtyTwo: '3.2rem',
    fifty: '5rem',
    eighty: '8rem',
    eightyFive: '8.5rem',
    oneHundred: '10rem',
    twoHundredTwentyFive: '22.5rem',
  },
};
