export const styles = {
  colors: {
    light: '#3b3b3b',
    greenContrast: '#43B27F',
    lightMode: '#EDFDF2',
    darkMode: '#080610',
    white: '#FFF',
    greyContrast: '#93B1A6',
  },
  percentage: {
    fifty: '50%',
    seventyFive: '75%',
    eighty: '80%',
    ninety: '90%',
  },
  viewPort: {
    height: {
      eighty: '80vh',
    },
  },
  unitsInREMToPX: {
    six: '0.6rem',
    ten: '1rem',
    twelve: '1.2rem',
    fourteen: '1.4rem',
    sixteen: '1.6rem',
    eighteen: '1.8rem',
    twenty: '2rem',
    twentyTwo: '2.2rem',
    twentyFour: '2.4rem',
    twentyEigth: '2.8rem',
    thirty: '3rem',
    thirtyTwo: '3.2rem',
    forty: '4rem',
    fifty: '5rem',
    eighty: '8rem',
    eightyFive: '8.5rem',
    oneHundred: '10rem',
    twoHundredTwentyFive: '22.5rem',
    fiveHundred: '50rem',
  },
};
