import { Spline_Sans } from 'next/font/google';
import { Metadata } from 'next';

import Header from '@/components/Header';
import { ChildrenProps } from '@/@types/children-props';

import './globals.css';

export const metadata: Metadata = {
  title: 'Organiza Real',
  description: 'Generated by create next app',
};

const splineSans = Spline_Sans({ subsets: ['latin'] });

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="pt-BR" className="h-screen">
      <body className={`${splineSans.className} bg-theme-light`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
