import { Inter } from 'next/font/google';
import { Metadata } from 'next';

import { ChildrenProps } from '@/@types/children-props';

import './globals.css';

export const metadata: Metadata = {
  title: 'Organiza Real',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="pt-BR" className="h-screen">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
